#微服务端口号
server:
  port: 8001


#微服务名称
spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver      #mysql驱动包
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    url: jdbc:mysql://localhost:3306/springcloud2020?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456


# mybatis设置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kevin.springcloud.entities   #所有Entity别名类所在包


